/** Códigos de isenção de IVA SAF-T (AO) — cópia de @nexus/agt-xml/exemptions (o browser não importa esse pacote). */
export const TAX_EXEMPTIONS: ReadonlyArray<{ code: string; hint: string }> = [
  { code: 'M00', hint: 'Contribuinte no regime simplificado' },
  { code: 'M02', hint: 'Operação não sujeita a IVA' },
  { code: 'M04', hint: 'Contribuinte no regime de exclusão' },
  { code: 'M10', hint: 'Bens alimentares (anexo I do CIVA)' },
  { code: 'M11', hint: 'Medicamentos (fins terapêuticos e profiláticos)' },
  { code: 'M12', hint: 'Cadeiras de rodas e equipamento para pessoas com deficiência' },
  { code: 'M13', hint: 'Livros (incluindo digitais)' },
  { code: 'M14', hint: 'Arrendamento para habitação' },
  { code: 'M15', hint: 'Operações sujeitas a SISA' },
  { code: 'M16', hint: 'Jogos de fortuna ou azar' },
  { code: 'M17', hint: 'Transporte colectivo de passageiros' },
  { code: 'M18', hint: 'Intermediação financeira' },
  { code: 'M19', hint: 'Seguros de saúde e do ramo vida' },
  { code: 'M20', hint: 'Produtos petrolíferos (anexo II)' },
  { code: 'M21', hint: 'Ensino' },
  { code: 'M22', hint: 'Serviços médicos e sanitários (hospitais, clínicas)' },
  { code: 'M23', hint: 'Transporte de doentes (ambulâncias)' },
  { code: 'M24', hint: 'Equipamentos médicos para estabelecimentos de saúde' },
  { code: 'M30', hint: 'Exportação de bens' },
  { code: 'M31', hint: 'Abastecimento de embarcações (alto mar)' },
  { code: 'M32', hint: 'Abastecimento de aeronaves (internacional)' },
  { code: 'M33', hint: 'Abastecimento de embarcações de salvamento/pesca' },
  { code: 'M34', hint: 'Embarcações e aeronaves (transmissão, reparação, aluguer)' },
  { code: 'M35', hint: 'Relações diplomáticas e consulares' },
  { code: 'M36', hint: 'Organismos internacionais' },
  { code: 'M37', hint: 'Tratados e acordos internacionais' },
  { code: 'M38', hint: 'Transporte internacional de pessoas' },
  { code: 'M80', hint: 'Importação de bens isentos' },
  { code: 'M81', hint: 'Importação de ouro/moeda pelo BNA' },
  { code: 'M82', hint: 'Importação para calamidades naturais' },
  { code: 'M83', hint: 'Importação para operações petrolíferas' },
  { code: 'M84', hint: 'Importação de moeda estrangeira (bancos)' },
  { code: 'M85', hint: 'Importação no âmbito de tratados internacionais' },
  { code: 'M86', hint: 'Importação em relações diplomáticas' },
  { code: 'M90', hint: 'Regimes aduaneiros (importação sob controlo)' },
  { code: 'M91', hint: 'Bens para zonas/depósitos francos' },
  { code: 'M92', hint: 'Bens em regimes aduaneiros suspensivos' },
  { code: 'M93', hint: 'Trânsito, draubaque ou importação temporária' },
  { code: 'M94', hint: 'Reimportação de bens exportados' },
];
